// List Users
export const GET_LIST_USER_REQUEST = "GET_LIST_USER";
export const GET_LIST_USER_SUCCESS = "GET_LIST_USER_SUCCESS";
export const GET_LIST_USER_FAILURE = "GET_LIST_USER_FAILURE";

// Login
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";


// Get list banner
export const GET_LIST_BANNER_REQUEST = "GET_LIST_BANNER_REQUEST"
export const GET_LIST_BANNER_SUCCESS = "GET_LIST_BANNER_SUCCESS"
export const GET_LIST_BANNER_FAILURE = "GET_LIST_BANNER_FAILURE"